import type { MetadataRoute } from "next";
import { APP_URL } from "@/lib/config";

/**
 * The four pages worth indexing.
 *
 * ── WHY IT IS A HAND-WRITTEN LIST ──
 * Everything else in the product is either behind a session, keyed to one
 * recipient, or transient. A sitemap generated by walking the route tree would
 * therefore be mostly wrong, and wrong in the direction that matters: it would
 * advertise /inbox and /u/<token> to a crawler that has no business with
 * either. Four entries typed out is not a maintenance burden; four hundred
 * derived from a filesystem walk would be a liability.
 *
 * The set is asserted in tests/seo.test.ts against the routes that are
 * publicly reachable per proxy.ts, so a new marketing page that nobody adds
 * here is caught rather than silently unlisted.
 *
 * `lastModified` is deliberately absent. A build timestamp would tell crawlers
 * every page changed on every deploy, which is a claim that stops being
 * believed; and there is no per-page edit date to use instead. Omitting the
 * field says "no opinion", which is true.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: `${APP_URL}/`,
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${APP_URL}/pricing`,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      // The only page on the site somebody can act on without an account.
      url: `${APP_URL}/contact`,
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${APP_URL}/terms`,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${APP_URL}/privacy`,
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];
}
